# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  # Frontend in development mode with hot reload
  frontend:
    build:
      target: development  # Use development build stage
    ports:
      - "5173:5173"  # Vite dev server port
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8004
      - VITE_APP_TITLE=Agent Network Sandbox (Dev)
    volumes:
      - ./frontend/src:/app/src  # Mount source for hot reload
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Longer start period for dev server

  # Orchestrator in development mode with enhanced logging
  orchestrator:
    environment:
      - ORCHESTRATOR_DEBUG=true
      - ORCHESTRATOR_LOG_LEVEL=DEBUG
      - ORCHESTRATOR_ENVIRONMENT=development
    volumes:
      # Mount source for development (if needed)
      - ./agents/orchestrator/src:/app/src